/-
Copyright (c) 2025 Wallpaper Groups Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import WallpaperGroups.PointGroup.RotationReflection

/-!
# Cyclic Point Groups

This file defines the cyclic point groups Cₙ as subgroups of O(2).

## Main definitions

* `CyclicPointGroup n` - The cyclic group Cₙ = ⟨R_{2π/n}⟩ ⊂ O(2)
* `DihedralPointGroup n` - The dihedral group Dₙ = ⟨R_{2π/n}, S₀⟩ ⊂ O(2)

## Main results

* `CyclicPointGroup.card` - |Cₙ| = n
* `isCyclic_cyclicPointGroup` - Cₙ is cyclic
* `CyclicPointGroup.le_dihedral` - Cₙ ≤ Dₙ
-/

namespace WallpaperGroups.PointGroup

open WallpaperGroups.Euclidean

/-- The cyclic point group Cₙ is generated by rotation by 2π/n.

For n = 1: C₁ = {I} (trivial group)
For n = 2: C₂ = {I, R_π}
For n ≥ 3: Cₙ = {I, R_{2π/n}, R_{4π/n}, ..., R_{2(n-1)π/n}}

blueprint: def:cyclic_point_group -/
def CyclicPointGroup (n : ℕ) [NeZero n] : Subgroup OrthogonalGroup2 :=
  Subgroup.closure {rotationMatrix' (2 * Real.pi / n)}

/-- The dihedral point group Dₙ is generated by rotation by 2π/n and reflection S₀.

Dₙ contains n rotations and n reflections, so |Dₙ| = 2n.

blueprint: def:dihedral_point_group -/
def DihedralPointGroup (n : ℕ) [NeZero n] : Subgroup OrthogonalGroup2 :=
  Subgroup.closure {rotationMatrix' (2 * Real.pi / n), reflectionMatrix' 0}

-- =============================================================================
-- Basic lemmas about C₁, C₂
-- =============================================================================

/-- C₁ is the trivial subgroup.

blueprint: lem:C1_trivial -/
lemma CyclicPointGroup.one : CyclicPointGroup 1 = ⊥ := by
  unfold CyclicPointGroup
  have h1 : (2 * Real.pi / (1 : ℕ) : ℝ) = 2 * Real.pi := by norm_num
  rw [h1]
  have h : rotationMatrix' (2 * Real.pi) = 1 := by
    apply Subtype.ext
    simp only [rotationMatrix', Submonoid.coe_one, rotationMatrix_two_pi]
  rw [h]
  exact Subgroup.closure_singleton_one

/-- C₂ consists of the identity and 180° rotation.

blueprint: lem:C2_rotation -/
lemma CyclicPointGroup.two :
    (CyclicPointGroup 2 : Set OrthogonalGroup2) = {1, rotationMatrix' Real.pi} := by
  have h : (2 * Real.pi / (2 : ℕ) : ℝ) = Real.pi := by norm_num
  unfold CyclicPointGroup
  rw [h, ← Subgroup.zpowers_eq_closure, zpowers_eq_pair_of_orderOf_two _ orderOf_rotationMatrix'_pi]

-- =============================================================================
-- Cₙ ⊆ SO(2) (rotations preserve orientation)
-- =============================================================================

lemma CyclicPointGroup.subset_SO2 (n : ℕ) [NeZero n] :
    (CyclicPointGroup n : Set OrthogonalGroup2) ⊆ SpecialOrthogonalGroup2 := by
  intro x hx
  simp only [SetLike.mem_coe, CyclicPointGroup, SpecialOrthogonalGroup2] at *
  have h_gen_in_SO2 : rotationMatrix' (2 * Real.pi / n) ∈ SpecialOrthogonalGroup2 := by
    simp only [SpecialOrthogonalGroup2, Subgroup.mem_mk]
    exact rotationMatrix'_det _
  have h_sub : Subgroup.closure {rotationMatrix' (2 * Real.pi / n)} ≤ SpecialOrthogonalGroup2 := by
    rw [Subgroup.closure_le]
    simp only [Set.singleton_subset_iff]
    exact h_gen_in_SO2
  exact h_sub hx

/-- Cₙ is a subgroup of Dₙ of index 2. -/
lemma CyclicPointGroup.le_dihedral (n : ℕ) [NeZero n] :
    CyclicPointGroup n ≤ DihedralPointGroup n := by
  unfold CyclicPointGroup DihedralPointGroup
  apply Subgroup.closure_mono
  intro x hx
  simp only [Set.mem_singleton_iff] at hx
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff]
  left
  exact hx

-- =============================================================================
-- Main theorems
-- =============================================================================

/-- The order of Cₙ is n.

blueprint: lem:cyclic_order -/
lemma CyclicPointGroup.card (n : ℕ) [NeZero n] :
    Nat.card (CyclicPointGroup n) = n := by
  have h_zpowers : CyclicPointGroup n = Subgroup.zpowers (rotationMatrix' (2 * Real.pi / n)) := by
    unfold CyclicPointGroup
    exact Subgroup.zpowers_eq_closure (rotationMatrix' (2 * Real.pi / n)) |>.symm
  rw [h_zpowers, Nat.card_zpowers]
  exact orderOf_rotationMatrix'_two_pi_div n

/-- The order of the rotation by 2π/n is n. -/
lemma orderOf_rotationMatrix'_generator (n : ℕ) [NeZero n] :
    orderOf (⟨rotationMatrix' (2 * Real.pi / n),
              Subgroup.subset_closure (Set.mem_singleton _)⟩ : CyclicPointGroup n) = n := by
  have h : orderOf (rotationMatrix' (2 * Real.pi / n)) = n := orderOf_rotationMatrix'_two_pi_div n
  let a : CyclicPointGroup n := ⟨rotationMatrix' (2 * Real.pi / n),
                                  Subgroup.subset_closure (Set.mem_singleton _)⟩
  have heq : orderOf (a : OrthogonalGroup2) = orderOf a := Subgroup.orderOf_coe a
  rw [← heq, h]

/-- Cₙ is a cyclic group. -/
instance isCyclic_cyclicPointGroup (n : ℕ) [NeZero n] : IsCyclic (CyclicPointGroup n) := by
  have h_zpowers : CyclicPointGroup n = Subgroup.zpowers (rotationMatrix' (2 * Real.pi / n)) := by
    unfold CyclicPointGroup
    exact Subgroup.zpowers_eq_closure (rotationMatrix' (2 * Real.pi / n)) |>.symm
  have h_eq : ∀ x : CyclicPointGroup n, (x : OrthogonalGroup2) ∈
              Subgroup.zpowers (rotationMatrix' (2 * Real.pi / n)) := by
    intro x
    rw [← h_zpowers]
    exact x.2
  use ⟨rotationMatrix' (2 * Real.pi / n), Subgroup.subset_closure (Set.mem_singleton _)⟩
  intro x
  obtain ⟨k, hk⟩ := Subgroup.mem_zpowers_iff.mp (h_eq x)
  use k
  apply Subtype.ext
  simp only [SubgroupClass.coe_zpow]
  exact hk

end WallpaperGroups.PointGroup
