/-
Copyright (c) 2025 Wallpaper Groups Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import WallpaperGroups.Euclidean.OrthogonalGroup

/-!
# Cyclic and Dihedral Point Groups

This file defines the cyclic point groups Cₙ and dihedral point groups Dₙ as
subgroups of O(2).

## Main definitions

* `CyclicPointGroup n` - The cyclic group Cₙ = ⟨R_{2π/n}⟩ ⊂ O(2)
* `DihedralPointGroup n` - The dihedral group Dₙ = ⟨R_{2π/n}, S₀⟩ ⊂ O(2)

## Main results

* `CyclicPointGroup.card` - |Cₙ| = n
* `DihedralPointGroup.card` - |Dₙ| = 2n
* `DihedralPointGroup.semidirectProduct` - Dₙ ≅ Cₙ ⋊ C₂
* `DihedralPointGroup.equivDihedralGroup` - Dₙ ≅ DihedralGroup n (Mathlib)
-/

namespace WallpaperGroups.PointGroup

open WallpaperGroups.Euclidean

/-- The cyclic point group Cₙ is generated by rotation by 2π/n.

For n = 1: C₁ = {I} (trivial group)
For n = 2: C₂ = {I, R_π}
For n ≥ 3: Cₙ = {I, R_{2π/n}, R_{4π/n}, ..., R_{2(n-1)π/n}}

blueprint: def:cyclic_point_group -/
def CyclicPointGroup (n : ℕ) [NeZero n] : Subgroup OrthogonalGroup2 :=
  Subgroup.closure {rotationMatrix' (2 * Real.pi / n)}

/-- The dihedral point group Dₙ is generated by rotation by 2π/n and reflection S₀.

Dₙ contains n rotations and n reflections, so |Dₙ| = 2n.

blueprint: def:dihedral_point_group -/
def DihedralPointGroup (n : ℕ) [NeZero n] : Subgroup OrthogonalGroup2 :=
  Subgroup.closure {rotationMatrix' (2 * Real.pi / n), reflectionMatrix' 0}

/-- C₁ is the trivial subgroup.

blueprint: lem:C1_trivial -/
lemma CyclicPointGroup.one : CyclicPointGroup 1 = ⊥ := by
  sorry

/-- C₂ consists of the identity and 180° rotation.

blueprint: lem:C2_rotation -/
lemma CyclicPointGroup.two :
    (CyclicPointGroup 2 : Set OrthogonalGroup2) = {1, rotationMatrix' Real.pi} := by
  sorry

/-- D₁ consists of the identity and one reflection, isomorphic to C₂.

blueprint: lem:D1_reflection -/
lemma DihedralPointGroup.one :
    (DihedralPointGroup 1 : Set OrthogonalGroup2) = {1, reflectionMatrix' 0} := by
  sorry

/-- D₂ is the Klein four-group.

blueprint: lem:D2_klein -/
lemma DihedralPointGroup.two_isKleinFour :
    Nonempty ((DihedralPointGroup 2 : Subgroup OrthogonalGroup2) ≃*
              ZMod 2 × ZMod 2) := by
  sorry

/-- The order of Cₙ is n.

blueprint: lem:cyclic_order -/
lemma CyclicPointGroup.card (n : ℕ) [NeZero n] :
    Nat.card (CyclicPointGroup n) = n := by
  sorry

/-- The order of Dₙ is 2n.

blueprint: lem:dihedral_order -/
lemma DihedralPointGroup.card (n : ℕ) [NeZero n] :
    Nat.card (DihedralPointGroup n) = 2 * n := by
  sorry

/-- Cₙ is a subgroup of Dₙ of index 2. -/
lemma CyclicPointGroup.le_dihedral (n : ℕ) [NeZero n] :
    CyclicPointGroup n ≤ DihedralPointGroup n := by
  sorry

/-- Cₙ is normal in Dₙ. -/
lemma CyclicPointGroup.normal_in_dihedral (n : ℕ) [NeZero n] :
    (CyclicPointGroup n).subgroupOf (DihedralPointGroup n) |>.Normal := by
  sorry

/-- Dₙ is a semidirect product Cₙ ⋊ C₂.

blueprint: lem:dihedral_structure -/
lemma DihedralPointGroup.semidirectProduct (n : ℕ) [NeZero n] :
    ∃ (φ : Multiplicative (ZMod 2) →* MulAut (Multiplicative (ZMod n))),
      Nonempty ((DihedralPointGroup n : Subgroup OrthogonalGroup2) ≃*
        Multiplicative (ZMod n) ⋊[φ] Multiplicative (ZMod 2)) := by
  sorry

/-- Dₙ ⊂ O(2) is isomorphic to Mathlib's DihedralGroup n.

blueprint: lem:dihedral_embedding -/
lemma DihedralPointGroup.equivDihedralGroup (n : ℕ) [NeZero n] :
    Nonempty ((DihedralPointGroup n : Subgroup OrthogonalGroup2) ≃* DihedralGroup n) := by
  sorry

/-- Cₙ consists of all elements of Dₙ with determinant 1. -/
lemma CyclicPointGroup.eq_dihedral_inter_SO2 (n : ℕ) [NeZero n] :
    (CyclicPointGroup n : Set OrthogonalGroup2) =
    (DihedralPointGroup n : Set OrthogonalGroup2) ∩ SpecialOrthogonalGroup2 := by
  sorry

end WallpaperGroups.PointGroup
